import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.io.StringReader

class GenAssemblyTest {
    fun runTest(prog:String, expected:String) {
        val lexers = listOf(Lexer(StringReader(prog),"input.fpl"))
        val output = compile(lexers, StopAt.ASSEMBLY)
        assertEquals(expected, output)
    }

    @Test
    fun helloWorld() {
        val prog = """
            extern fun print(s:String)

            fun main()
                print("Hello, World!")
        """.trimIndent()

        val expected = """
            # Generated by Falcon Compiler
            /topLevel:
            ret

            /main():
            sub SP, SP, 4
            stw R30, SP[0]
            ld R1, STRING0
            jsr /print(String)
            ldw R30, SP[0]
            add SP, SP, 4
            ret

            dcw 13
            STRING0: # Hello, World!
            dcw 1819043144
            dcw 1461726319
            dcw 1684828783
            dcw 33


        """.trimIndent()

        runTest(prog, expected)
    }

    @Test
    fun basicCallTest() {
        val prog = """
            fun add(a:Int, b:Int) -> Int
                return a + b

            fun main()
                var x = add(2,3)
        """.trimIndent()

        val expected = """
            # Generated by Falcon Compiler
            /topLevel:
            ret

            /add(Int,Int):
            # a = R1
            # b = R2
            add R8, R1, R2
            ret

            /main():
            # x = R1
            sub SP, SP, 4
            stw R30, SP[0]
            ld R1, 2
            ld R2, 3
            jsr /add(Int,Int)
            ldw R30, SP[0]
            add SP, SP, 4
            ret


        """.trimIndent()

        runTest(prog, expected)
    }

}