import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.io.StringReader

class GenAssemblyTest {
    fun runTest(prog:String, expected:String) {
        val lexers = listOf(Lexer(StringReader(prog),"input.fpl"))
        val output = compile(lexers, StopAt.ASSEMBLY)
        assertEquals(expected, output)
    }

    @Test
    fun helloWorld() {
        val prog = """
            extern fun print(s:String)

            fun main()
                print("Hello, World!")
        """.trimIndent()

        val expected = """
            # Generated by Falcon Compiler
            /topLevel:
            line "null" 0
            line "input.fpl" 1
            line "input.fpl" 1
            line "input.fpl" 3
            ret

            /main():
            sub SP, SP, 4
            stw R30, SP[0]
            line "input.fpl" 4
            ld R1, STRING0
            jsr /print(String)
            ldw R30, SP[0]
            add SP, SP, 4
            ret

            dcw 13
            STRING0: # Hello, World!
            dcw 1819043144
            dcw 1461726319
            dcw 1684828783
            dcw 33


        """.trimIndent()

        runTest(prog, expected)
    }

    @Test
    fun basicCallTest() {
        val prog = """
            fun add(a:Int, b:Int) -> Int
                return a + b

            fun main()
                var x = add(2,3)
        """.trimIndent()

        val expected = """
            # Generated by Falcon Compiler
            /topLevel:
            line "null" 0
            line "input.fpl" 1
            line "input.fpl" 1
            line "input.fpl" 4
            ret

            /add(Int,Int):
            # a = R1
            # b = R2
            line "input.fpl" 2
            add R8, R1, R2
            ret

            /main():
            # x = R1
            sub SP, SP, 4
            stw R30, SP[0]
            line "input.fpl" 5
            ld R1, 2
            ld R2, 3
            jsr /add(Int,Int)
            ldw R30, SP[0]
            add SP, SP, 4
            ret


        """.trimIndent()

        runTest(prog, expected)
    }

    @Test
    fun syscallTest() {
        val prog = """
            extern fun open(name:String) syscall 4

            fun main()
                open("test.txt")
        """.trimIndent()

        val expected = """
            # Generated by Falcon Compiler
            /topLevel:
            line "null" 0
            line "input.fpl" 1
            line "input.fpl" 1
            line "input.fpl" 3
            ret

            /main():
            line "input.fpl" 4
            ld R1, STRING0
            sys 4
            ret

            dcw 8
            STRING0: # test.txt
            dcw 1953719668
            dcw 1954051118


        """.trimIndent()

        runTest(prog, expected)
    }
}