`timescale 1 ns / 1ns
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Falcon5(

	//////////// Audio //////////
	// input 		          		AUD_ADCDAT,
	// inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);

logic clock;
logic reset;
logic locked;

logic         dcache_sdram_ready;
logic         dcache_sdram_request;
logic [25:0]  dcache_sdram_addr;
logic         dcache_sdram_write;
logic         dcache_sdram_burst;
logic [3:0]   dcache_sdram_wstrb;
logic [31:0]  dcache_sdram_wdata;
logic         dcache_sdram_rvalid;
logic [31:0]  dcache_sdram_rdata;
logic [25:0]  dcache_sdram_raddress;
logic         dcache_sdram_complete;

logic         cpu_aux_request;
logic [31:0]  cpu_aux_addr;
logic         cpu_aux_write;
logic [3:0]   cpu_aux_wstrb;
logic [31:0]  cpu_aux_wdata;
logic         cpu_aux_abort;
logic         cpu_aux_rvalid;
logic [31:0]  cpu_aux_rdata;
logic [8:0]   cpu_aux_rtag;
logic [31:0]  cpu_pc;

logic        hwregs_request;
logic        hwregs_write;
logic [15:0] hwregs_addr;
logic [3:0]  hwregs_wmask;
logic [31:0] hwregs_wdata;
logic        hwregs_rvalid;
logic [8:0]  hwregs_rtag;
logic [31:0] hwregs_rdata_regs;
logic [31:0] hwregs_rdata_audio;
logic [31:0] hwregs_rdata;
logic [31:0] vga_reg_rdata;

logic        iram_request;
logic        iram_write;
logic [15:0] iram_addr;
logic [3:0]  iram_wmask;
logic [31:0] iram_wdata;
logic        iram_rvalid;
logic [8:0]  iram_rtag;
logic [31:0] iram_rdata;

logic [2:0]  sdram_request;
logic        sdram_ready;
logic [25:0] sdram_address;
logic        sdram_write;
logic        sdram_burst;
logic [3:0]  sdram_wstrb;
logic [31:0] sdram_wdata;
logic [31:0] sdram_rdata;
logic [25:0] sdram_raddress;
logic [2:0]  sdram_rvalid;
logic        sdram_complete;

logic         cpu_icache_request;
logic [31:0]  cpu_icache_addr;
logic [8:0]   cpu_icache_tag;
logic         cpu_icache_ready;
logic         cpu_icache_rvalid;
logic [31:0]  cpu_icache_rdata;
logic [31:0]  cpu_icache_raddr;
logic [8:0]   cpu_icache_rtag;

logic         vga_sdram_request;
logic         vga_sdram_ready;
logic [25:0]  vga_sdram_address;
logic         vga_sdram_rvalid;
logic [31:0]  vga_sdram_rdata;
logic [25:0]  vga_sdram_raddress;
logic         vga_sdram_complete;

logic         blitr_sdram_request;
logic [25:0]  blitr_sdram_address;
logic         blitr_sdram_ready;
logic         blitr_sdram_rvalid;
logic [31:0]  blitr_sdram_rdata;
logic [25:0]  blitr_sdram_raddress;
logic         blitr_sdram_complete;

logic         blitw_sdram_request;
logic         blitw_sdram_ready;
logic [25:0]  blitw_sdram_address;
logic [3:0]   blitw_sdram_wstrb;
logic [31:0]  blitw_sdram_wdata;

logic         audio_sdram_request;
logic         audio_sdram_write;
logic [31:0]  audio_sdram_wdata;
logic         audio_sdram_ready;
logic [25:0]  audio_sdram_address;
logic         audio_sdram_rvalid;
logic [31:0]  audio_sdram_rdata;
logic [25:0]  audio_sdram_raddress;
logic         audio_sdram_complete;

logic         copper_sdram_ready;
logic         copper_sdram_request;
logic [25:0]  copper_sdram_address;
logic         copper_sdram_data_valid;
logic [31:0]  copper_sdram_rdata;
logic [25:0]  copper_sdram_raddress;
logic         copper_sdram_complete;

logic         copper_aux_request;
logic         copper_aux_ack;
logic [23:0]  copper_aux_address;
logic [31:0]  copper_aux_wdata;
logic [25:0]  hwregs_copper_address;
logic         hwregs_copper_start;



logic         hwregs_blit_valid;
logic [31:0]  hwregs_blit_command;
logic         hwregs_blit_privaledge;
logic [9:0]   blit_fifo_slots_free;
logic         cpu_read_overflow;
logic         cpu_stuck;


logic [9:0]  mouse_x;
logic [9:0]  mouse_y;
logic [9:0]  vga_row;
logic [9:0]  vga_col;
logic [2:0]  perf_count;
logic [9:0]  ledr;
logic [31:0] vga_frame_num;

logic fault_detected;


assign GPIO_1 = {blitw_sdram_wstrb,sdram_write, sdram_request, 2'b0,sdram_address};
assign GPIO_0[35:2] = {cpu_pc,perf_count};


pll  pll_inst (
    .refclk(CLOCK_50),
    .rst(1'b0),
    .outclk_0(clock),
    .outclk_1(DRAM_CLK),
    .locked(locked)
  );
always_ff @(posedge clock) begin
  reset <= !locked;
end

cpu  cpu_inst (
    .clock(clock),
    .reset(reset),
    .dcache_sdram_ready(dcache_sdram_ready),
    .dcache_sdram_request(dcache_sdram_request),
    .dcache_sdram_addr(dcache_sdram_addr),
    .dcache_sdram_write(dcache_sdram_write),
    .dcache_sdram_burst(dcache_sdram_burst),
    .dcache_sdram_wstrb(dcache_sdram_wstrb),
    .dcache_sdram_wdata(dcache_sdram_wdata),
    .dcache_sdram_rvalid(dcache_sdram_rvalid),
    .dcache_sdram_rdata(dcache_sdram_rdata),
    .dcache_sdram_raddress(dcache_sdram_raddress),
    .dcache_sdram_complete(dcache_sdram_complete),
    .cpu_aux_request(cpu_aux_request),
    .cpu_aux_addr(cpu_aux_addr),
    .cpu_aux_write(cpu_aux_write),
    .cpu_aux_wstrb(cpu_aux_wstrb),
    .cpu_aux_wdata(cpu_aux_wdata),
    .cpu_aux_abort(cpu_aux_abort),
    .cpu_aux_rvalid(cpu_aux_rvalid),
    .cpu_aux_rdata(cpu_aux_rdata),
    .cpu_aux_rtag(cpu_aux_rtag),
    .cpu_icache_request(cpu_icache_request),
    .cpu_icache_addr(cpu_icache_addr),
    .cpu_icache_tag(cpu_icache_tag),
    .cpu_icache_ready(cpu_icache_ready),
    .cpu_icache_rvalid(cpu_icache_rvalid),
    .cpu_icache_rdata(cpu_icache_rdata),
    .cpu_icache_raddr(cpu_icache_raddr),
    .cpu_icache_rtag(cpu_icache_rtag),
    .perf_count(perf_count),
    .cpu_pc(cpu_pc),
    .cpu_read_overflow(cpu_read_overflow),
    .cpu_stuck(cpu_stuck)
  );

assign hwregs_rdata = hwregs_rdata_regs | hwregs_rdata_audio;

aux_decoder  aux_decoder_inst (
    .clock(clock),
    .reset(reset),
    .cpu_aux_request(cpu_aux_request),
    .cpu_aux_write(cpu_aux_write),
    .cpu_aux_addr(cpu_aux_addr),
    .cpu_aux_wstrb(cpu_aux_wstrb),
    .cpu_aux_wdata(cpu_aux_wdata),
    .cpu_aux_abort(cpu_aux_abort),
    .cpu_aux_rvalid(cpu_aux_rvalid),
    .cpu_aux_rdata(cpu_aux_rdata),
    .cpu_aux_rtag(cpu_aux_rtag),
    .copper_aux_request(copper_aux_request),
    .copper_aux_ack(copper_aux_ack),
    .copper_aux_address(copper_aux_address),
    .copper_aux_wdata(copper_aux_wdata),
    .hwregs_request(hwregs_request),
    .hwregs_write(hwregs_write),
    .hwregs_addr(hwregs_addr),
    .hwregs_wmask(hwregs_wmask),
    .hwregs_wdata(hwregs_wdata),
    .hwregs_rvalid(hwregs_rvalid),
    .hwregs_rtag(hwregs_rtag),
    .hwregs_rdata(hwregs_rdata),
    .iram_request(iram_request),
    .iram_write(iram_write),
    .iram_addr(iram_addr),
    .iram_wmask(iram_wmask),
    .iram_wdata(iram_wdata),
    .iram_rvalid(iram_rvalid),
    .iram_rtag(iram_rtag),
    .iram_rdata(iram_rdata)
  );

  hwregs  hwregs_inst (
    .clock(clock),
    .reset(reset),
    .hwregs_request(hwregs_request),
    .hwregs_write(hwregs_write),
    .hwregs_addr(hwregs_addr),
    .hwregs_wmask(hwregs_wmask),
    .hwregs_wdata(hwregs_wdata),
    .hwregs_rvalid(hwregs_rvalid),
    .hwregs_rtag(hwregs_rtag),
    .hwregs_rdata(hwregs_rdata_regs),
    .hwregs_blit_valid(hwregs_blit_valid),
    .hwregs_blit_command(hwregs_blit_command),
    .hwregs_blit_privaledge(hwregs_blit_privaledge),
    .blit_fifo_slots_free(blit_fifo_slots_free),
    .HEX0(HEX0),
    .HEX1(HEX1),
    .HEX2(HEX2),
    .HEX3(HEX3),
    .HEX4(HEX4),
    .HEX5(HEX5),
    .KEY(KEY),
    .LEDR(ledr),
    .SW(SW),
    .UART_TX(GPIO_0[0]),
    .UART_RX(GPIO_0[1]),
    .GPIO_0(),
    .GPIO_1(),
    .PS2_CLK(PS2_CLK),
    .PS2_DAT(PS2_DAT),
    .PS2_CLK2(PS2_CLK2),
    .PS2_DAT2(PS2_DAT2),
    .SCL(FPGA_I2C_SCLK),
    .SDA(FPGA_I2C_SDAT),
    .mouse_x(mouse_x),
    .mouse_y(mouse_y),
    .perf_count(perf_count),
    .vga_row(vga_row),
    .cpu_pc(cpu_pc[23:0]),
    .vga_frame_num(vga_frame_num),
    .hwregs_copper_address(hwregs_copper_address),
    .hwregs_copper_start(hwregs_copper_start)
  );

assign LEDR[9:0] = ledr[9:0] | {cpu_read_overflow,cpu_stuck,fault_detected, 7'b0};


// verilator lint_off PINCONNECTEMPTY
sdram_arbiter  sdram_arbiter_inst (
    .clk(clock),
    .reset(reset),
    .m1_request(vga_sdram_request),
    .m1_ready(vga_sdram_ready),
    .m1_write(1'b0),
    .m1_burst(1'b1),
    .m1_address(vga_sdram_address),
    .m1_wdata(32'bx),
    .m1_wstrb(4'bx),
    .m1_rvalid(vga_sdram_rvalid),
    .m1_raddress(vga_sdram_raddress),
    .m1_rdata(vga_sdram_rdata),
    .m1_complete(vga_sdram_complete),
    .m2_request(audio_sdram_request),
    .m2_ready(audio_sdram_ready),
    .m2_write(audio_sdram_write),
    .m2_burst(1'b1),
    .m2_address(audio_sdram_address),
    .m2_wdata(audio_sdram_wdata),
    .m2_wstrb(4'hf),
    .m2_rvalid(audio_sdram_rvalid),
    .m2_raddress(audio_sdram_raddress),
    .m2_rdata(audio_sdram_rdata),
    .m2_complete(audio_sdram_complete),
    .m3_request(dcache_sdram_request),
    .m3_ready(dcache_sdram_ready),
    .m3_write(dcache_sdram_write),
    .m3_burst(dcache_sdram_burst),
    .m3_address(dcache_sdram_addr),
    .m3_wdata(dcache_sdram_wdata),
    .m3_wstrb(dcache_sdram_wstrb),
    .m3_rvalid(dcache_sdram_rvalid),
    .m3_raddress(dcache_sdram_raddress),
    .m3_rdata(dcache_sdram_rdata),
    .m3_complete(dcache_sdram_complete),
    .m4_request(blitr_sdram_request),
    .m4_ready(blitr_sdram_ready),
    .m4_write(1'b0),
    .m4_burst(1'b1),
    .m4_address(blitr_sdram_address),
    .m4_wdata(32'bx),
    .m4_wstrb(4'bx),
    .m4_rvalid(blitr_sdram_rvalid),
    .m4_raddress(blitr_sdram_raddress),
    .m4_rdata(blitr_sdram_rdata),
    .m4_complete(blitr_sdram_complete),
    .m5_request(copper_sdram_request),
    .m5_ready(copper_sdram_ready),
    .m5_write(1'b0),
    .m5_burst(1'b1),
    .m5_address(copper_sdram_address),
    .m5_wdata(32'bx),
    .m5_wstrb(4'b0),
    .m5_rvalid(copper_sdram_data_valid),
    .m5_raddress(copper_sdram_raddress),
    .m5_rdata(copper_sdram_rdata),
    .m5_complete(copper_sdram_complete),
    .m6_request(blitw_sdram_request),
    .m6_ready(blitw_sdram_ready),
    .m6_write(1'b1),
    .m6_burst(1'b0),
    .m6_address(blitw_sdram_address),
    .m6_wdata(blitw_sdram_wdata),
    .m6_wstrb(blitw_sdram_wstrb),
    .m6_rvalid(),
    .m6_raddress(),
    .m6_rdata(),
    .m6_complete(),
    .sdram_request(sdram_request),
    .sdram_ready(sdram_ready),
    .sdram_address(sdram_address),
    .sdram_write(sdram_write),
    .sdram_burst(sdram_burst),
    .sdram_wstrb(sdram_wstrb),
    .sdram_wdata(sdram_wdata),
    .sdram_raddress(sdram_raddress),
    .sdram_rdata(sdram_rdata),
    .sdram_rvalid(sdram_rvalid),
    .sdram_complete(sdram_complete)
  );

  sdram_controller  sdram_controller_inst (
    .clock(clock),
    .reset(reset),
    .sdram_request(sdram_request),
    .sdram_ready(sdram_ready),
    .sdram_address(sdram_address),
    .sdram_write(sdram_write),
    .sdram_burst(sdram_burst),
    .sdram_wstrb(sdram_wstrb),
    .sdram_wdata(sdram_wdata),
    .sdram_rdata(sdram_rdata),
    .sdram_raddress(sdram_raddress),
    .sdram_rvalid(sdram_rvalid),
    .sdram_complete(sdram_complete),
    .DRAM_ADDR(DRAM_ADDR),
    .DRAM_BA(DRAM_BA),
    .DRAM_CAS_N(DRAM_CAS_N),
    .DRAM_CKE(DRAM_CKE),
    .DRAM_CS_N(DRAM_CS_N),
    .DRAM_DQ(DRAM_DQ),
    .DRAM_LDQM(DRAM_LDQM),
    .DRAM_RAS_N(DRAM_RAS_N),
    .DRAM_UDQM(DRAM_UDQM),
    .DRAM_WE_N(DRAM_WE_N)
  );

instruction_ram  instruction_ram_inst (
    .clock(clock),
    .iram_request(iram_request),
    .iram_write(iram_write),
    .iram_address(iram_addr),
    .iram_wmask(iram_wmask),
    .iram_wdata(iram_wdata),
    .iram_rvalid(iram_rvalid),
    .iram_rtag(iram_rtag),
    .iram_rdata(iram_rdata),
    .ifetch_iram_request(cpu_icache_request),
    .ifetch_iram_ready(cpu_icache_ready),
    .ifetch_iram_address(cpu_icache_addr),
    .ifetch_iram_wdata({23'b0,cpu_icache_tag}),
    .ifetch_iram_rdata(cpu_icache_rdata),
    .ifetch_iram_raddr(cpu_icache_raddr),
    .ifetch_iram_rtag(cpu_icache_rtag),
    .ifetch_iram_rvalid(cpu_icache_rvalid)
  );

vga2  vga_inst (
    .clock(clock),
    .reset(reset),
    .vga_reg_request(hwregs_request),
    .vga_reg_write(hwregs_write),
    .vga_reg_address(hwregs_addr),
    .vga_reg_wdata(hwregs_wdata),
    .vga_reg_rdata(vga_reg_rdata),
    .start_of_frame(start_of_frame),
    .VGA_CLK(VGA_CLK),
    .VGA_R(VGA_R),
    .VGA_G(VGA_G),
    .VGA_B(VGA_B),
    .VGA_HS(VGA_HS),
    .VGA_VS(VGA_VS),
    .VGA_SYNC_N(VGA_SYNC_N),
    .VGA_BLANK_N(VGA_BLANK_N),
    .vga_sdram_request(vga_sdram_request),
    .vga_sdram_ready(vga_sdram_ready),
    .vga_sdram_address(vga_sdram_address),
    .vga_sdram_rvalid(vga_sdram_rvalid),
    .vga_sdram_rdata(vga_sdram_rdata),
    .vga_sdram_raddress(vga_sdram_raddress),
    .vga_sdram_complete(vga_sdram_complete)
    // // .mouse_x(mouse_x),
    // // .mouse_y(mouse_y),
    // .vga_row(vga_row),
    // .vga_col(vga_col),
    // .vga_frame_num(vga_frame_num)
  );

blitter  blitter_inst (
    .clock(clock),
    .reset(reset),
    .hwregs_blit_valid(hwregs_blit_valid),
    .hwregs_blit_command(hwregs_blit_command),
    .hwregs_blit_privaledge(hwregs_blit_privaledge),
    .blit_fifo_slots_free(blit_fifo_slots_free),
    .blitr_sdram_request(blitr_sdram_request),
    .blitr_sdram_address(blitr_sdram_address),
    .blitr_sdram_ready(blitr_sdram_ready),
    .blitr_sdram_rvalid(blitr_sdram_rvalid),
    .blitr_sdram_rdata(blitr_sdram_rdata),
    .blitr_sdram_raddress(blitr_sdram_raddress),
    .blitr_sdram_complete(blitr_sdram_complete),
    .blitw_sdram_request(blitw_sdram_request),
    .blitw_sdram_ready(blitw_sdram_ready),
    .blitw_sdram_address(blitw_sdram_address),
    .blitw_sdram_wstrb(blitw_sdram_wstrb),
    .blitw_sdram_wdata(blitw_sdram_wdata),
    .fault_detected(fault_detected)
  );

audio  audio_inst (
    .clock(clock),
    .reset(reset),
    .hwregs_request(hwregs_request),
    .hwregs_write(hwregs_write),
    .hwregs_addr(hwregs_addr),
    .hwregs_wdata(hwregs_wdata),
    .hwregs_rdata(hwregs_rdata_audio),
    .AUD_XCK(AUD_XCK),
    .AUD_BCLK(AUD_BCLK),
    .AUD_DACLRCK(AUD_DACLRCK),
    .AUD_DACDAT(AUD_DACDAT),
    .sdram_request(audio_sdram_request),
    .sdram_ready(audio_sdram_ready),
    .sdram_write(audio_sdram_write),
    .sdram_wdata(audio_sdram_wdata),
    .sdram_address(audio_sdram_address),
    .sdram_rvalid(audio_sdram_rvalid),
    .sdram_raddress(audio_sdram_raddress),
    .sdram_rdata(audio_sdram_rdata),
    .sdram_complete(audio_sdram_complete)
  );

copper  copper_inst (
    .clock(clock),
    .reset(reset),
    .hwregs_copper_start(hwregs_copper_start),
    .hwregs_copper_address(hwregs_copper_address),
    .hwregs_copper_busy(hwregs_copper_busy),
    .copper_sdram_ready(copper_sdram_ready),
    .copper_sdram_request(copper_sdram_request),
    .copper_sdram_address(copper_sdram_address),
    .copper_sdram_data_valid(copper_sdram_data_valid),
    .copper_sdram_rdata(copper_sdram_rdata),
    .copper_sdram_raddress(copper_sdram_raddress),
    .copper_sdram_complete(copper_sdram_complete),
    .copper_aux_request(copper_aux_request),
    .copper_aux_ack(copper_aux_ack),
    .copper_aux_address(copper_aux_address),
    .copper_aux_wdata(copper_aux_wdata),
    .vga_xpos(vga_col),
    .vga_ypos(vga_row)
  );

endmodule
