class Token (val location: Location, val kind: TokenKind, val value: String) {
    override fun toString(): String = value
}

enum class TokenKind(val value: String, val lineContinues: Boolean) {
    EOF           ("<End of File>", false),
    EOL           ("<End of Line>", true),
    INDENT        ("<Indent>", false),
    DEDENT        ("<Dedent>", false),
    IDENTIFIER    ("<Identifier>", false),
    INTLITERAL    ("<Integer Literal>", false),
    STRINGLITERAL ("<String Literal>", false),
    CHARLITERAL   ("<Character Literal>", false),
    REALLITERAL   ("<Real Literal>", false),
    PLUS          ("+", true),
    MINUS         ("-", true),
    STAR          ("*", true),
    SLASH         ("/", true),
    PERCENT       ("%", true),
    AMPERSAND     ("&", true),
    BAR           ("|", true),
    CARET         ("^", true),
    EQ            ("=", true),
    NEQ           ("!=", true),
    LT            ("<", true),
    LTE           ("<=", true),
    GT            (">", true),
    GTE           (">=", true),
    COLON         (":", true),
    COMMA         (",", true),
    OPENB         ("(", true),
    CLOSEB        (")", false),
    OPENSQ        ("[", true),
    CLOSESQ       ("]", false),
    OPENCL        ("{", true),
    CLOSECL       ("}", false),
    DOT           (".", true),
    DOTDOT        ("..", true),
    QMARK         ("?", false),
    QMARKQMARK    ("??", false),
    EMARK         ("!", true),
    AND           ("and", true),
    OR            ("or", true),
    NOT           ("not", true),
    LSL           ("lsl", true),
    LSR           ("lsr", true),
    ASR           ("asr", true),
    ARROW         ("->", true),
    VAL           ("val", true),
    VAR           ("var", true),
    IF            ("if", true),
    ELSIF         ("elsif", true),
    THEN          ("then", true),
    ELSE          ("else", false),
    END           ("end", false),
    RETURN        ("return", false),
    WHILE         ("while", true),
    FOR           ("for", true),
    IN            ("in", true),
    BREAK         ("break", false),
    CONTINUE      ("continue", false),
    FUN           ("fun", true),
    REPEAT        ("repeat", false),
    UNTIL         ("until", true),
    NEW           ("new", true),
    LOCAL         ("local", true),
    CONST         ("const", true),
    ARRAY         ("Array", false),
    CLASS         ("class", true),
    EXTERN        ("extern", true),
    ERROR         ("<error>", false);

    override fun toString(): String = value

    companion object {
        val toKind = entries.associateBy{it.value}
    }
}